# Generated by Django 4.0.2 on 2022-02-24 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'webp', 'jpeg'])]),
        ),
    ]
