# Generated by Django 4.0.2 on 2022-03-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_last_seen'),
        ('posts', '0007_post_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('verificated', models.CharField(choices=[('Received', 'Received'), ('Verified', 'Verified')], default='Received', max_length=8)),
                ('job', models.PositiveSmallIntegerField(choices=[(1, 'Bloger/Actor'), (2, 'Programmer'), (3, 'Football Player'), (4, 'Sportsman'), (5, 'Motion/Designer/IT'), (6, 'Other')], default=6)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
