# Generated by Django 4.0.2 on 2022-02-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='follows',
        ),
        migrations.DeleteModel(
            name='RelationShip',
        ),
    ]
