# Generated by Django 4.0.2 on 2022-02-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_follows_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='follow', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Unfollow', 'Unfollow')], max_length=8),
        ),
    ]
