# Generated by Django 4.0.2 on 2022-03-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
        ('notification', '0004_notification_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
