# Generated by Django 4.0.2 on 2022-03-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_post_id_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follower', 'Follower'), ('like', 'Like'), ('comment', 'Comment'), ('message', 'Message')], max_length=20),
        ),
    ]
