# Generated by Django 4.0.2 on 2022-03-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='image',
            new_name='img_src',
        ),
    ]
