# Generated by Django 4.0.2 on 2022-07-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmodel_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmodel',
            options={'verbose_name': 'Chat message', 'verbose_name_plural': 'Chat messages'},
        ),
    ]
